# API Gateway
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # === AUTH SERVICE ===
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: auth-h2-console
          uri: lb://auth-service
          predicates:
            - Path=/auth/h2-console/**
          filters:
            - RewritePath=/auth/h2-console(?<segment>/?.*), /h2-console${segment}

        # === MEMBERSHIP SERVICE ===
        - id: membership-service
          uri: lb://membership-service
          predicates:
            - Path=/api/membership/**
        - id: membership-h2-console
          uri: lb://membership-service
          predicates:
            - Path=/membership/h2-console/**
          filters:
            - RewritePath=/membership/h2-console(?<segment>/?.*), /h2-console${segment}

        # === PAYMENT SERVICE ===
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
        - id: payment-h2-console
          uri: lb://payment-service
          predicates:
            - Path=/payment/h2-console/**
          filters:
            - RewritePath=/payment/h2-console(?<segment>/?.*), /h2-console${segment}

        # === NOTIFICATION SERVICE ===
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
        - id: notification-h2-console
          uri: lb://notification-service
          predicates:
            - Path=/notification/h2-console/**
          filters:
            - RewritePath=/notification/h2-console(?<segment>/?.*), /h2-console${segment}

        # === GROUP SERVICE ===
        - id: group-service
          uri: lb://group-service
          predicates:
            - Path=/api/group/**
        - id: group-h2-console
          uri: lb://group-service
          predicates:
            - Path=/group/h2-console/**
          filters:
            - RewritePath=/group/h2-console(?<segment>/?.*), /h2-console${segment}

        # === CYCLE PAYOUT ORCHESTRATION SERVICE ===
        - id: cycle-payout-orchestration-service
          uri: lb://cycle-payout-orchestration-service
          predicates:
            - Path=/api/cycle/**
        - id: cycle-h2-console
          uri: lb://cycle-payout-orchestration-service
          predicates:
            - Path=/cycle/h2-console/**
          filters:
            - RewritePath=/cycle/h2-console(?<segment>/?.*), /h2-console${segment}

        # === TRANSACTION SERVICE ===
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transaction/**
        - id: transaction-h2-console
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/h2-console/**
          filters:
            - RewritePath=/transaction/h2-console(?<segment>/?.*), /h2-console${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
