server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Service routes
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: membership-service
          uri: lb://membership-service
          predicates:
            - Path=/api/membership/**

        # H2 Console routes - FIXED CONFIGURATION
        - id: auth-h2-console
          uri: lb://auth-service
          predicates:
            - Path=/auth/h2-console/**
          filters:
            - RewritePath=/auth/h2-console(?<segment>/?.*), /h2-console$\{segment}

        - id: membership-h2-console
          uri: lb://membership-service
          predicates:
            - Path=/membership/h2-console/**
          filters:
            - RewritePath=/membership/h2-console(?<segment>/?.*), /h2-console$\{segment}

  config:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: pX6r4kz3e2l9f5aD1cB8v7gN0jM5qW2yL4iH9oP3uK6tF1xZ0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG