# Auth Service
server:
  port: 9001

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
