# Cycle Payout Orchestration Service
server:
  port: 9006

spring:
  application:
    name: cycle-payout-orchestration-service
  datasource:
    url: jdbc:h2:mem:cycledb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
