server:
  port: 8080

spring:
  application:
    name: discovery-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true    # API Gateway should register with Eureka
    fetch-registry: true          # API Gateway should fetch registry from Eureka
  instance:
    hostname: localhost
    prefer-ip-address: false      # Typically false when using hostname
