server:
  port: 9010

spring:
  application:
    name: membership-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true

 
