# Notification Service
server:
  port: 9004

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:h2:mem:notificationdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
