# Payment Service
server:
  port: 9003

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

payment:
  momo:
    base-url: https://sandbox.momodeveloper.mtn.com 
    subscription-key: YOUR_SUBSCRIPTION_KEY             
    environment: sandbox                               
    api-user: YOUR_API_USER                             
    api-key: YOUR_API_KEY                                
