# Transaction Service
server:
  port: 9007

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:h2:mem:transactiondb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

services:
  group-service:
    url: localhost:8081

  membership-service:
    url: localhost:8081
